apiVersion: batch/v1
kind: Job

metadata:
  name: {{ template "elastic.name" . }}-log-setter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  backoffLimit: 0
  parallelism: 1
  ttlSecondsAfterFinished: 60

  template:
    metadata:
      name: {{ template "elastic.name" . }}-log-setter
      labels:
        {{- include "commonLabels" . | nindent 8 }}

    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "elastic.name" . }}-log-setter-pod
        image: appropriate/curl:3.1
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - configMapRef:
              name: {{ include "elastic.configMapName" . }}
        resources:
          limits:
            cpu: "40m"
            memory: "32Mi"

        command:
        - sh
        - -c
        - |-
          #!/bin/sh
          VULAS_CHART="{{ template "elastic.name" . }}"
          VULAS_LOG_ORIGIN="log-level-setter.sh"
          {{- include "logFunctions" . | nindent 10 }}

          http () {
              local path="${1}"
              if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
              else
                BASIC_AUTH=''
              fi
              curl -XGET --write-out %{http_code} -s --output /dev/null -k --fail ${BASIC_AUTH} ${{ .Release.Name | upper }}_ELASTICSEARCH_SERVICE_HOST:9200${path}
          }
          status_code=$(http "/_cluster/health?{{ .Values.elasticsearch.clusterHealthCheckParams }}")
          attempts=0

          while [ $status_code -ne "200" ]; do
            status_code=$(http "/_cluster/health?{{ .Values.elasticsearch.clusterHealthCheckParams }}")
            attemps=$((attempts + 1))
            if [ $attempts -ge "15" ]; then
              _vulas_error "Ran out of attempts. Job cancelled."
              exit 127
            fi
            _vulas_error "Cluster is not ready. Sleeping for 10 seconds"
            sleep 10
          done

          _vulas_info "Cluster is up and ready, attempting to inject configurations"
          {{- if .Values.elasticsearch.debug }}
          status_code=$(curl --write-out %{http_code} -s --output /dev/null -X PUT "${{ .Release.Name | upper }}_ELASTICSEARCH_SERVICE_HOST:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d '
          {
            "transient": {
              "logger.org.elasticsearch.transport": "trace"
            }
          }
          ')
          {{- else }}
          status_code=$(curl --write-out %{http_code} -s --output /dev/null -X PUT "${{ .Release.Name | upper }}_ELASTICSEARCH_SERVICE_HOST:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d '
          {
            "transient": {
              "logger.org.elasticsearch.transport": "error"
            }
          }
          ')
          {{- end }}

          if [ $status_code -eq "200" ]; then
            _vulas_info "Log level is set"
            exit 0
          else
            _vulas_error "Error setting log level"
            exit 127
          fi
