matrix:
  include:
    - name: OpenJDK8 - Run all the test on the Open JVM
      language: java
      jdk: openjdk8
      cache:
        timeout: 1000
        directories:
        - $HOME/.m2
      before_cache:
        - rm -rf $HOME/.m2/repository/com/sap/research/security/vulas/
      install:
        - "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"
      script: mvn -e -B -P soot,gradle -Dit.test='!IT01_PatchAnalyzerIT, IT*, *IT, *ITCase' -DfailIfNoTests=false --settings .travis/settings.xml clean install

    #- name: OracleJDK8 - Run all the test on the Oracle JVM
    #  language: java
    #  jdk: oraclejdk8
    #  cache:
    #    timeout: 1000
    #    directories:
    #    - $HOME/.m2
    #  before_cache:
    #    - rm -rf $HOME/.m2/repository/com/sap/research/security/vulas/
    #  install:
    #    - "echo 'Skipping install stage, dependencies will be downloaded during build and test stages.'"
    #  script: mvn -e -B -P soot,gradle -Dit.test='!IT01_PatchAnalyzerIT, IT*, *IT, *ITCase' -DfailIfNoTests=false --settings .travis/settings.xml clean install

    - name: Docker (skip Java tests) - Build the Modules' Jars, Create vital containers, Check if they stay alive for more than 20 seconds
      language: bash
      sudo: required
      services:
        - docker
      before_install:
        - docker -v
        - docker-compose -v
        - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
        - cp .travis/.env docker/.env
      install:
        - docker build --tag vulas-travis -f docker/Dockerfile --build-arg http_proxy= --build-arg https_proxy= .
        - docker run -it --rm -v ${PWD}/docker:/exporter --env-file ./docker/.env -e mvn_flags=-DskipTests vulas-travis
      script:
        - (cd docker && docker-compose up -d --build)
        - sh .travis/check.sh
      after_failure:
        - docker images
        - docker ps -as
        - (cd docker && docker-compose logs)
    
   # - name: Docker - Build the Modules' Jars, Run all Java tests, Create vital containers, Check if they stay alive for more than 20 seconds
   #   language: bash
   #   sudo: required
   #   services:
   #     - docker
   #   before_install:
   #     - docker -v
   #     - docker-compose -v
   #     - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
   #     - cp .travis/.env docker/.env
   #   install:
   #     - docker build --tag vulas-travis -f docker/Dockerfile --build-arg http_proxy= --build-arg https_proxy= .
   #     - docker run -it --rm -v ${PWD}/docker:/exporter --env-file ./docker/.env -e mvn_flags='-q -P soot,gradle -Dit.test=!IT01_PatchAnalyzerIT,IT*,*IT,*ITCase -DfailIfNoTests=false --settings .travis/settings.xml' vulas-travis
   #   script:
   #     - (cd docker && docker-compose up -d --build)
   #     - sh .travis/check.sh
   #   after_failure:
   #     - docker images
   #     - docker ps -as
   #     - (cd docker && docker-compose logs)

    - name: Docs - Build and check the docs for dead links
      language: bash
      sudo: required
      services:
        - docker
      before_install:
        - docker -v
        - docker-compose -v
      install:
        - docker build --tag docs ./docs
        - docker build --tag checklinks -f ./docs/Dockerfile.checklinks ./docs
        - docker network create docs
      script:
        - docker run --rm --network=docs  -d --name docs --hostname docs -p 8000:8000 docs
        - sleep 20
        - docker run --rm --network=docs --name checklinks checklinks
      after_failure:
        - docker images
        - docker ps -as
        - (cd docker && docker logs)

notifications:
  email: false
