#     Suggestion : number of frontendbugs replicas should
#                  be approximatively the amount of backend replicas
#                  in order to maximize uptime of the said service
replicas: 2

extraConfigs: {}
podNetworkPolicy:
  enabled: false

podPriorityClass:
  # If .Values.global.podPriorityClass.enabled and spec is {}
  # defaults to
  #   globalDefault: false
  #   value: 300
  #   preemptionPolicy: Never
  spec: {}

horizontalPodAutoScaler:
  enabled: true
  # If set to {} and .Values.horizontalPodAutoScaler.enabled=true
  # defaults to
  #   metrics:
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       targetAverageUtilization: 70
  # Else set to a map that respects scheme defined in
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#horizontalpodautoscalerlist-v1-autoscaling
  spec: {}

# Sets logging level for shell scripts
debug: true

podDisruptionBudget: {}
  #    Warning :  this won't be applied unless the replicas
  #               values are >= 2
  # minAvailable: 1

selfAntiAffinity:
  soft: true
  weight: 100

image:
  pullPolicy: "IfNotPresent"
  registry: {}
  registryPort: {}
  # Jetty web server used to push new approved vulnerabilities
  name: "vulas/vulnerability-assessment-tool-frontend-bugs"
  # Footprint:
  # - size: 177.16MB
  tag: "3.1.7-SNAPSHOT-jib"

  livenessProbe:
    # Overall time before container is killed by k8s :
    # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * failureThreshold)
    # = 78s ~= 1.3min
    # Average start time for container ~ 7600ms
    enabled: true
    initialDelaySeconds: 8
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 2

  readinessProbe:
    # Worst case scenario time before container is considered unready by k8s :
    # initialDelaySeconds + ((periodSeconds + timeoutSeconds) * successThreshold)
    # = 75s ~= 1.25min
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 2

  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
    requests:
      memory: "100Mi"
      cpu: "100m"

  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    privileged: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
      - ALL
      add:
      - SYS_TIME
      - NET_ADMIN
