apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ include "nginx-ingress.main.ingressName" . }}
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressController.ingressClass }}

    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    {{- $subPath := .Values.global.subPath }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^{{ $subPath }}/(.*)$ /$1 break;

    nginx.ingress.kubernetes.io/server-snippet: |
      aio                 threads;
      proxy_cache_key     "$request_method$host$request_uri$http_x_vulas_space";
      proxy_cache         STATIC;
      add_header          X-Cache-Date $upstream_http_date;
      add_header          X-Proxy-Cache $upstream_cache_status;

spec:
  rules:
    - http:
        paths:
          {{ $release := .Values.global.managedRelease }}
          - path: {{ $subPath }}/apps/
            backend:
              serviceName: {{ $release }}-frontend-apps
              servicePort: 8080
          - path: {{ $subPath }}/backend/
            backend:
              serviceName: {{ $release }}-restbackend
              servicePort: 8091
          - path: /backend/
            backend:
              serviceName: {{ $release }}-restbackend
              servicePort: 8091
          - path: {{ $subPath }}/cia/
            backend:
              serviceName: {{ $release }}-restlibutils
              servicePort: 8092
          - path: /cia/
            backend:
              serviceName: {{ $release }}-restlibutils
              servicePort: 8092
          {{- if or (not .Values.ingressController.authIngress) (not .Values.ingressController.authIngress.enabled) }}
          - path: {{ $subPath }}/bugs/
            backend:
              serviceName: {{ $release }}-frontend-bugs
              servicePort: 8080
          {{- end }}
