apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "envConfigMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{ $release := .Release.Name }}
  {{- with .Values.global.dbCredentials }}
  spring.datasource.url: jdbc:postgresql://{{ $release }}-db-pool:5432/{{ .postgres_db }}
  FLYWAY_URL: jdbc:postgresql://{{ $release }}-db-master:5432/{{ .postgres_db }}
  {{- end }}

  {{- if .Values.debug }}
  DEBUG: "true"
  LOGGING_LEVEL_ROOT: "INFO"
  {{- end }}

  vulas.backend.coverageService.licenseConfidenceThreshold: {{ .Values.licenseConfidenceThreshold  | quote }}
  vulas.backend.coverageService.langConfidenceThreshold: {{ .Values.langConfidenceThreshold  | quote }}
  vulas.shared.cia.serviceUrl: "http://{{ $release }}-restlibutils:8092/cia"
  vulas.backend.cveCache.refetchAllMs: "7200000"
  vulas.backend.cveCache.refetchSingleMs: "10000"
  vulas.backend.cveCache.serviceUrl: ""
  vulas.backend.space.doNotDelete: ""
  vulas.backend.space.doNotClean: ""
  vulas.backend.space.doNotModify: ""
  vulas.shared.cve.serviceUrl: ""
  vulas.shared.jira.serviceUrl: ""
  vulas.shared.jira.projectId: ""
  vulas.shared.jira.componentId: ""
  vulas.shared.jira.browseIssueUrl: ""
  vulas.shared.jira.createIssueUrl: ""
  vulas.backend.allApps.mailSubject: ""
  vulas.backend.smtp.sender: ""
  vulas.backend.smtp.host: ""
  vulas.backend.smtp.port: ""
  vulas.backend.smtp.user: ""
  vulas.backend.smtp.pwd: ""
  vulas.backend.frontend.apps.dl.regex: ""
  vulas.backend.frontend.apps.dl.example: ""
  vulas.backend.frontend.apps.sw.id.label: "Software ID"
  vulas.backend.frontend.apps.sw.id.url: ""
  vulas.backend.frontend.apps.sw.id.mandatory: "false"
  vulas.backend.frontend.apps.sw.id.link: ""
  vulas.backend.frontend.apps.sw.id.db.key: ""
  vulas.backend.frontend.apps.sw.id.regex: ""
  vulas.backend.frontend.apps.wiki.url: "https://sap.github.io/vulnerability-assessment-tool/user/"
  vulas.core.noThreads: "AUTO"
