{{- if .Values.persistentVolume -}}
{{- if .Values.persistentVolume.nfs -}}
apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ template "pvName" . }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  accessModes:
  {{- if .Values.persistentVolume.nfs }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}

  capacity:
    storage: {{ .Values.persistentVolume.storage }}

  nfs:
    server: {{ .Values.persistentVolume.nfs.server }}
    path: {{ .Values.persistentVolume.nfs.path }}
{{- end -}}
{{- end -}}
