apiVersion: v1
appVersion: "3.1.7-SNAPSHOT"

description: A Chart for fluentd logging
name: fluentd
version: 0.1.1

kubeVersion: ">=v1.15.0"
description: Helm Chart for elasticsearch + kibana for the vulnerability-assessment-tool
keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://eclipse.github.io/steady
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
