apiVersion: v1
appVersion: 0.25.0
name: nginx-ingress
version: v0.1.1

kubeVersion: ">=v1.15.0"
description: Helm Chart for vulnerability-assessment-tool-admin nginx stack
keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://sap.github.io/vulnerability-assessment-tool/
sources:
  - https://github.com/SAP/vulnerability-assessment-tool


maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
tillerVersion: v2.14.2
