apiVersion: v1
appVersion: "3.1.7-SNAPSHOT"
name: vulnerability-assessment-tool-monitoring
version: v0.1.1

kubeVersion: ">=v1.15.0"
description: Helm Chart for vulnerability-assessment-tool monitoring services
keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://eclipse.github.io/steady
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

maintainers:
  - name: "holla"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
