apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "envConfigMapName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

data:
  {{- $release := .Release.Name }}
  HOSTNAME: {{ $release }}-db-pool
  DELAY_START_UP: {{ .Values.startUpDelay | quote }}
  BACKOFF_DURATION: {{ .Values.backoffDuration | quote }}
  {{- if .Values.debug }}
  DEBUG: "true"
  {{- end }}
  {{- if .Values.deployment.enabled }}
  {{- if .Values.persistentVolume }}
  PATCHEVAL_OPTS: -bug "{{ .Values.cronJob.bugs | default "" }}" -folder {{ .Values.persistentVolume.mountPath | default "/patcheval-data" }} -j -h {{ .Values.cronJob.delay | default "0" }} -p {{ .Values.cronJob.delay | default "6" }}
  {{- else }}
  PATCHEVAL_OPTS: -bug "{{ .Values.cronJob.bugs | default "" }}" -folder "/patcheval-data" -j -h {{ .Values.cronJob.delay | default "0" }} -p {{ .Values.cronJob.delay | default "6" }}
  {{- end }}
  {{- else }}
  PATCHEVAL_OPTS: -bug "{{ .Values.cronJob.bugs | default "" }}" -folder {{ if .Values.persistentVolume }}{{ .Values.persistentVolume.mountPath }}{{ else }}"/patcheval-data"{{ end }}
  {{- end }}

  vulas.shared.cia.serviceUrl: "http://{{ $release }}-restlibutils:8092/cia"
  vulas.patchEval.onlyAddNewResults: "true"
  vulas.shared.backend.serviceUrl: "http://{{ $release }}-restbackend:8091/backend"
  {{- if .Values.extraConfigs }}
  {{- toYaml .Values.extraConfigs | nindent 2 }}
  {{- end }}
