{{- if .Values.persistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ template "pvcName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  accessModes:
  {{- if .Values.persistentVolume.nfs }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
{{- end -}}
