apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ template "postgres.slave.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}

spec:
  serviceName: {{ .Release.Name }}-db-slave-headless

  updateStrategy:
    type: {{ .Values.postgres.slave.updateStrategy }}

  {{- if and .Values.global.slaveReplicas (ge (int .Values.global.slaveReplicas) 1) }}
  replicas: {{ .Values.global.slaveReplicas }}
  {{- else if and .Values.global.replicationFactor (ge (mul .Values.global.replicationFactor .Values.global.masterReplicas ) 1) }}
  replicas: {{ (mul .Values.global.masterReplicas .Values.global.masterReplicas) }}
  {{- else }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      {{- include "postgres.slave.enrichedLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "postgres.slave.enrichedLabels" . | nindent 8 }}
      {{- if .Values.postgres.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      {{- end }}
    spec:
      {{- if .Values.global.podPriorityClass.enabled }}
      {{- if .Values.postgres.slave.podPriorityClass }}
      priorityClassName: {{ template "postgres.slave.priorityClassName" . }}
      {{- end }}
      {{- end }}
      automountServiceAccountToken: false
      initContainers:
        - name: {{ template "postgres.slave.name" . }}-init-container
          image: {{ template "containerName" .Values.postgres.image.initContainer }}
          imagePullPolicy: {{ .Values.postgres.image.initContainer.pullPolicy }}
          ports:
          - name: db
            containerPort: 5432
          command:
          - sh
          - -c
          - . /vulas/replica-init.sh

          envFrom:
            - secretRef:
                name: {{ template "postgres.secretName" . }}
          env:
            - name: PGDATA
              value: {{ .Values.postgres.slave.pvcMountPath }}/pgdata

          volumeMounts:
            - name: {{ template "postgres.script.configMapName" . }}
              mountPath: /vulas/replica-init.sh
              subPath: replica-init.sh

            - name: {{ template "postgres.slave.pvcName" . }}
              mountPath: {{ .Values.postgres.slave.pvcMountPath }}

          {{ if .Values.postgres.image.initContainer.securityContext -}}
          securityContext:
            {{- toYaml .Values.postgres.image.initContainer.securityContext | nindent 12 }}
          {{- end }}
          {{ if .Values.postgres.image.initContainer.resources -}}
          resources:
            {{- toYaml .Values.postgres.image.initContainer.resources | nindent 12 }}
          {{- end }}

      containers:
        - name: {{ template "postgres.slave.name" . }}-container
          image: {{ template "containerName" .Values.postgres.image.mainContainer }}
          imagePullPolicy: {{ .Values.postgres.image.mainContainer.pullPolicy }}
          args: ['-c', 'config_file=/etc/postgres.conf']
          ports:
          - name: db
            containerPort: 5432

          envFrom:
          - secretRef:
              name: {{ template "postgres.secretName" . }}

          env:
            - name: PGDATA
              value: {{ .Values.postgres.slave.pvcMountPath }}/pgdata
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PGPOOL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "pgpool.secretName" . }}
                  key: PCP_USER
            - name: PGPOOL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "pgpool.secretName" . }}
                  key: PCP_PASSWORD

          volumeMounts:
          - name: {{ template "postgres.slave.pvcName" . }}
            mountPath: {{ .Values.postgres.slave.pvcMountPath }}
          - name: {{ template "postgres.configMapName" . }}
            mountPath: /etc/postgres.conf
            subPath: postgres.conf
          - name: {{ template "postgres.configMapName" . }}
            mountPath: /etc/pg_hba.conf
            subPath: pg_hba.conf
          - name: {{ template "postgres.configMapName" . }}
            mountPath: /etc/replica.conf
            subPath: replica.conf
          - name: {{ template "postgres.script.configMapName" . }}
            mountPath: /docker-entrypoint-initdb.d/01-postgres-users-setup.sh
            subPath: 01-postgres-users-setup.sh
          - name: dshm
            mountPath: /dev/shm

          {{- if .Values.postgres.slave.readinessProbe }}
          {{- if .Values.postgres.slave.readinessProbe.enabled }}
          {{- with .Values.postgres.slave.readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            exec:
              command:
                - 'psql'
                - '-c'
                - 'SELECT 1'
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.postgres.slave.livenessProbe }}
          {{- if .Values.postgres.slave.livenessProbe.enabled }}
          {{- with .Values.postgres.slave.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            exec:
              command:
                - 'sh'
                - '-c'
                - 'exec pg_isready --host $POD_IP'
          {{- end }}
          {{- end }}
          {{- end }}
          {{/*- if .Values.postgres.image.mainContainer.securityContext }}
          securityContext:
            {{- toYaml .Values.postgres.image.mainContainer.securityContext | nindent 12 }}
          {{- end */}}
          {{- if .Values.postgres.slave.resources }}
          resources:
            {{- toYaml .Values.postgres.slave.resources | nindent 12 }}
          {{- end }}

        {{- if .Values.postgres.metrics.enabled }}
        - name: {{ template "postgres.slave.name" . }}-exporter-container
          image: {{ template "containerName" .Values.postgres.image.exporterContainer }}
          imagePullPolicy: {{ .Values.postgres.image.exporterContainer.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9187
          env:
          {{- with .Values.global.dbCredentials }}
          - name: DATA_SOURCE_NAME
            value: "postgresql://{{ .postgres_user }}:{{ .postgres_password }}@localhost:5432/?sslmode=disable"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PG_EXPORTER_CONSTANT_LABELS
            value: "origin=${POD_NAME}"
          {{- end }}
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
        {{- end }}

      volumes:
        - name: {{ template "postgres.configMapName" . }}
          configMap:
            name: {{ template "postgres.configMapName" . }}
        - name: {{ template "postgres.script.configMapName" . }}
          configMap:
            name: {{ template "postgres.script.configMapName" . }}
            defaultMode: 0755
        - name: {{ template "postgres.slave.pvcName" . }}
          persistentVolumeClaim:
            claimName: {{ template "postgres.slave.pvcName" . }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "3Gi"

      terminationGracePeriodSeconds: {{ int .Values.postgres.slave.terminationGracePeriodSeconds }}
      {{- if .Values.postgres.slaveAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{- if .Values.postgres.slaveAntiAffinity.soft }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{ end }}
          - weight: {{ .Values.postgres.slaveAntiAffinity.weight }}
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: [{{ include "name" . }}]
                - key: app.kubernetes.io/instance
                  operator: In
                  values: [{{ template "postgres.slave.name" . }}]
              topologyKey: "kubernetes.io/hostname"
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: {{ template "postgres.slave.pvcName" . }}
      labels:
        {{- include "postgres.slave.enrichedLabels" . | nindent 8 }}

    spec:
      accessModes: [{{ .Values.postgres.slave.accessModes | quote }}]
      resources:
        requests:
          storage: {{ .Values.postgres.slave.requests.storage | quote }}
